server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true


spring:
  profiles:
    include: oauth
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 903684776912-1mjksa1mapb1i2dncofmnnd4khf8ln7i.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: http://localhost:9090/login/oauth2/code/google


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  main:
    allow-bean-definition-over: true